### PR TITLE
My first pull request in this project

### PR DESCRIPTION
**Pull request by tddpirate**

### CODE REVIEW

**Comment by ripper234** [comment]
Please update the title of this PR: What is it trying to achieve/solve?

I mean, is it a bunch of different unrelated commits, or is there a unifying theme?

**Comment by dmtintner** [comment]
this pull request is no longer relevant

**Comment by ripper234** [comment]
@dmtintner 

Is it because the code changed already so the submitted PR lags behind?

**Comment by dmtintner** [comment]
Yes

**Pull request closed without merging**
